#! /bin/bash

PROFILE=""
DATABASE=""
ENGINE=""
MIGRATIONS_FOLDER="example/migrations"

# go run cmd/main.go -p $PROFILE -d $DATABASE -e $ENGINE -f $MIGRATIONS_FOLDER -i

# To run the built file
# ./raiway -p $PROFILE -d $DATABASE -e $ENGINE -f $MIGRATIONS_FOLDER -i